version: '3.8'

services:
  atonixforge:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - REACT_APP_DB_HOST=atonixforgedb
      - REACT_APP_DB_PORT=5432
      - REACT_APP_DB_NAME=atonixforgedb
      - REACT_APP_DB_USER=guxegdsa
      - REACT_APP_DB_PASSWORD=FRTAGl6innovation

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: atonixforgedb
      POSTGRES_USER: guxegdsa
      POSTGRES_PASSWORD: FRTAGl6innovation 
    ports:
      - "5432:5432"
