image: cdrx/pyruby:latest

stages:
  - build
  - test
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - echo "Building the project..."
    - python setup.py build

test:
  stage: test
  script:
    - echo "Running tests..."
    - pytest

deploy:
  stage: deploy
  script:
    - echo "Deploying the project..."
    - ./deploy.sh
  only:
    - main

your_job:
  stage: test
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    # Your other Python commands here
    - ruby -v
    # Your Ruby commands here
