image: atlassian/default-image:latest

pipelines:
  default:
    - step:
        name: Build and Push Docker Image
        runs-on:
          - self.hosted
          - linux
        services:
          - docker
        caches:
          - docker
        script:
          - echo "Building Docker image..."
          - docker build -t ofidohubvm/atonixcorp:latest .
          - echo "Logging in to Docker Hub..."
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          - echo "Pushing Docker image to Docker Hub..."
          - docker push ofidohubvm/atonixcorp:latest
    - step:
        name: Run Docker Container
        runs-on:
          - self.hosted
          - linux
        services:
          - docker
        script:
          - echo "Running Docker container..."
          - docker run -d -p 8000:8000 --name atonixcorp-container ofidohubvm/atonixcorp:latest

definitions:
  services:
    docker:
      memory: 2048
