image: python:3.8

pipelines:
  default:
    - parallel:
        - step:
            name: Test
            caches:
              - pip
            script:
              - cd Workshop/atonixcore/AtonixCorp
              - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
              - pip install pytest
              - ls -R tests  # List the contents of the tests directory
              - pytest -v tests/* --junitxml=test-reports/report.xml
        - step:
            name: Lint code
            script:
              - cd Workshop/atonixcore/AtonixCorp
              - pip install flake8
              - flake8 . --extend-exclude=dist,build --show-source --statistics
