
version: '3.9'

services:
  backend:
    build:
      context: ./Workshop/atonixcore
    image: atonixcofoo
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Workshop/atonixcore:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db_backend

  frontend:
    build:
      context: ./Workshop/atonixforge
    container_name: frontend
    volumes:
      - ./Workshop/atonixforge:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  environment:
    build:
      context: ./Workshop/environments
    container_name: environment
    volumes:
      - ./Workshop/environments:/env
    command: python /env/atonixcore/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db_environment

  db_backend:
    image: postgres:13
    container_name: db_backend
    volumes:
      - db_data_backend:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: atonixcofoodb
      POSTGRES_USER: guxegdsa
      POSTGRES_PASSWORD: atonixcofoobd

  db_environment:
    image: postgres:13
    container_name: db_environment
    volumes:
      - db_data_environment:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: atonixcofoodb
      POSTGRES_USER: guxegdsa
      POSTGRES_PASSWORD: atonixcofoobd

volumes:
  db_data_backend:
  db_data_environment:
