version: '3.8'

services:
  atonixcorpvm:
    image: atonixcorpvm
    container_name: atonixcorpvm_container
    environment:
      MYSQL_DATABASE: atonixcofoodb
      MYSQL_USER: admin
      MYSQL_PASSWORD: sf9x7ha2tcinn
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      POSTGRES_DB: atonixcorpvmdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: sf9x7ha2tcinn
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - "2222:2222"
      - "6379:6379"
      - "13308:3306"   # Port for MySQL
      - "15432:5432"
      - "51327:80"
      - "50121:8080"
      - "59876:59876"
    depends_on:
      - mysql
      - postgres

  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: sf9x7ha2tcinn
      MYSQL_DATABASE: atonixcofoodb
      MYSQL_USER: admin
      MYSQL_PASSWORD: sf9x7ha2tcinn
    ports:
      - "13308:3306"   # Port for MySQL
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: sf9x7ha2tcinn
      POSTGRES_DB: atonixcorpvmdb
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mysql_data:
  postgres_data:
