apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secret
type: Opaque
data:
  gitlab-token: { base64-encoded-token } # Replace with your base64-encoded token
  gitlab-username: { base64-encoded-username } # Replace with your base64-encoded username
  gitlab-password: { base64-encoded-password } # Replace with your base64-encoded password
  gitlab-email: { base64-encoded-email } # Replace with your base64-encoded email
