[build]
  base = "Workshop/AtonixCorpWebApp"
  publish = "Workshop/AtonixCorpWebApp/public"
  command = "cd Workshop/AtonixCorpWebApp && npm run build"

[dev]
  command = "npm start"
  targetPort = 3000
  framework = "create-react-app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200