[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "build"  # Corrected the publish path

[dev]
  command = "npm start"
  targetPort = 3000
  framework = "create-react-app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200