apiVersion: apps/v1
kind: Deployment
metadata:
  name: atonixinsight-deployments
  namespace: atonixcorpvm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atonixinsight
  template:
    metadata:
      labels:
        app: atonixinsight
    spec:
      containers:
      - name: atonixinsight
        image: docker.io/ofidohubvm/atonixinsight:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "db"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "sf9x7ha2tcinn"
        - name: DB_NAME
          value: "atonixcorpinsightdb"
      imagePullSecrets:
      - name: mydockerkeyring
