version: "3.8"

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 atonixcorp.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A atonixcorp worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
