# harness.yaml
application:
  name: AtonixCorp
  description: hardware software
  services:
    - name: atonixcorp
      artifactType: Docker
      artifactSource:
        type: DockerRegistry
        dockerRegistryUrl: https://index.docker.io/v1/
        imageName: atonixcorp
        tag: latest
  environments:
    - name: Dev_atonixcorp
      type: Non-Prod
      infrastructureDefinitions:
        - name: DevInfraatonixcorp
          cloudProviderType: Kubernetes
          namespace: dev-atonixcorp
    workflow:
    - name: DeployToDev
      type: Basic
      steps:
        - stepType: DeployService
          serviceName: atonixcorpservices
          environmentName: Dev_atonixcorp
          infrastructureDefinitionName: DevInfraatonixcorp
