apiVersion: v1
kind: ConfigMap
metadata:
  name: atonixcofoo
  namespace: atonixcorp-system
data:
  config.yaml: |
    ci_access:
      projects:
        - id: 65936411
    agents:
      atonixcorp:
        token:
