version: "3"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "192.168.1.100:8000:8000"
    environment:
      - DEBUG=True
