version: '3.8'

services:
  atonixforge:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/atonixforge
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: atonixforge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: