# permissions for end users to edit coreoperatorgoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: coreoperatorgo
    app.kubernetes.io/managed-by: kustomize
  name: coreoperatorgo-editor-role
rules:
- apiGroups:
  - cache.atonixcorp.org
  resources:
  - coreoperatorgoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.atonixcorp.org
  resources:
  - coreoperatorgoes/status
  verbs:
  - get
