---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cache.atonixcorp.org
  resources:
  - coreoperatorgoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.atonixcorp.org
  resources:
  - coreoperatorgoes/finalizers
  verbs:
  - update
- apiGroups:
  - cache.atonixcorp.org
  resources:
  - coreoperatorgoes/status
  verbs:
  - get
  - patch
  - update
