apiVersion: apps/v1
kind: Deployment
metadata:
  name: atonixforge-deployment
  namespace: atonixcorp-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atonixforge
  template:
    metadata:
      labels:
        app: atonixforge
    spec:
      containers:
      - name: atonixforge
        image: ofidohubvm/atonixforge:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-registry-secret
