apiVersion: v1
kind: Service
metadata:
  name: atonixforge-service
  namespace: coreoperatorgo-system
spec:
  selector:
    app: atonixforge
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
