apiVersion: v1
kind: Service
metadata:
  name: atonixforge-service
  namespace: atonixcorp-system
spec:
  selector:
    app: atonixforge
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
