apiVersion: apps/v1
kind: Deployment
metadata:
  name: atonixcore-deployment
  namespace: atonixcorp-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atonixcore
  template:
    metadata:
      labels:
        app: atonixcore
    spec:
      containers:
      - name: atonixcore
        image: ofidohubvm/atonixcore:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: docker-registry-secret
