apiVersion: v1
kind: Service
metadata:
  name: atonixcorp-service
  namespace: atonixcorp
spec:
  selector:
    app: atonixcorp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: http-personal
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: http-doc
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
