name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '3.x'

    - name: Install Jekyll and Bundler
      run: |
        gem install jekyll bundler

    - name: Generate controller-gen file
      run: |
        # Ensure controller-gen is available
        chmod +x bin/controller-gen
        ./bin/controller-gen

    - name: Build the site
      run: bundle exec jekyll build
