name: atonixcorp Docker image CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Load .env file
        run: |
          echo "DOCKER_API_TOKEN=$(grep DOCKER_API_TOKEN Backend/.env | cut -d '=' -f2)" >> $GITHUB_ENV
          echo "DOCKER_USERNAME=$(grep DOCKER_USERNAME Backend/.env | cut -d '=' -f2)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo ${{ env.DOCKER_API_TOKEN }} | docker login -u ${{ env.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ofidohubvm/atonixcorp .

      - name: Push Docker image
        run: |
          docker tag atonixcorp:latest ${{ env.DOCKER_USERNAME }}/atonixcorp:latest
          docker push ${{ env.DOCKER_USERNAME }}/atonixcorp:latest
